addresses:
  file: 'addresses.csv'
  table: 'addresses1'
  notes: False
  datatypes: 'object'
  date_columns: ['adr_Date']
cases:
  file: 'cases.csv'
  table: 'cases'
  notes: False
  datatypes: 'object'
  date_columns: ['cas_Open_Date','cas_Closed_Date', 'cas_Crime_Date','cas_Arrest_Date','cas_Date_Bail_Posted','cas_Date_Bail_Set','cas_Entry_Date','cas_ArraignDate']
custody_statuses:
  file: 'custody_statuses.csv'
  table: 'custody_statuses'
  notes: True
  date_columns: ['cust_Date_Entered']
memo_main:
  file: 'memo_main.csv'
  table: 'memo_main'
  notes: True
  date_columns: ['mem_Date']
names:
  file: 'names.csv'
  table: 'names'
  notes: False
  date_columns: ['nam_DOB']
results:
  file: 'results.csv'
  table: 'results'
  notes: False
  date_columns: ['res_Date']
loi:
  file: 'loi.csv'
  table: 'loi'
  notes: False
  date_columns: ['loi_System_Date', 'loi_DOB']
dispositions:
  file: 'dispositions.csv'
  table: 'dispositions'
  notes: True
  date_columns: ['dsp_Date']
events:
  file: 'events.csv'
  table: 'events'
  notes: True
  date_columns: ['evt_Event_Date']
